---
# tasks file for elasticsearch-cerebro

- name: Download lmenez/cerebro
  get_url:
    url: >-
      https://github.com/lmenezes/cerebro/releases/download/v
      {{- elastic_cerebro_version }}/cerebro-
      {{- elastic_cerebro_version }}.tgz
    dest: /opt/cerebro-{{elastic_cerebro_version}}.tgz
    mode: 0640

- name: Create program folder
  file:
    path: /opt/cerebro-{{elastic_cerebro_version}}
    state: directory

- name: Extract tarball
  unarchive:
    remote_src: yes
    src: /opt/cerebro-{{elastic_cerebro_version}}.tgz
    dest: /opt/
    creates: /opt/cerebro-{{elastic_cerebro_version}}/README.md
  notify:
    - restart elastic-cerebro

- name: Template out the configuration
  template:
    src: application.j2
    dest: /opt/cerebro-{{elastic_cerebro_version}}/conf/application.conf
  tags: elasticsearch-cerebro:config
  notify:
    - restart elastic-cerebro

- name: Template out the service file
  template:
    src: cerebro_service.j2
    dest: /etc/systemd/system/cerebro.service
  notify:
    - restart elastic-cerebro

- name: Ensure service is started
  service:
    name: cerebro
    enabled: true
    state: started
